### ISSUE TITLE
Nem írja az üzeneteket a zónára lépésnél pedig engedtem a player-move-eventet

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#11]

**Comment by benjaminforras** [comment]
A config.yml fájl frissítve lett?
( https://raw.githubusercontent.com/TryHardDood/myZone/v1.1/src/main/resources/config.yml )

**Comment by andris155** [comment]
igen ez van benne.
```
# +----------------------------------------------------+
# <                       myZone                       >
# <                 Configuration file                 >
# <                     config.yml                     >
# +----------------------------------------------------+

# You can change the default localization.
Locale: hu

# You don't need to give the players Worldedit permissions.
# The players need to select a region with this tool.
createTool: WOOD_SPADE

# You don't need to give the players Worldedit permissions.
# The players can check the zones info.
checkTool: WOOD_SWORD

Delay:
  checkTool: 2
  
Zone:
  Regex: '[^a-zA-Z0-9_\p{L}+]'

# Economy
Economy:
  Enabled: false
  Create: 50
  Delete: 50
  Flag: 50
  Expand: 50
  Member:
    Add: 50
    Remove: 50
  Owner:
    Add: 50
    Remove: 50

# Disabled in these worlds.
DisabledWorlds:
  - Spawn
  - SurvivalGames
  - event
  - plotworld
  
# Enable or disable the option to show the welcome/farewell messages.
# Permission: Whether it require a permission to enable/disable the message.
Messages:
  Title:
    Enabled: true
    Permission: false
  ActionBar:
    Enabled: false
    Permission: false
  BossBar:
    Enabled: false
    Permission: false

# Example:
# For a 25x256x25 zone you have to add this under (50, 256, 50): myzone.zone.max-size.1:
# (25, 256, 25): myzone.zone.max-size.2
# When you add this permission 'myzone.zone.max-size.2' the player will have a zone restriction of (25, 256, 25).
#
# To restrict the max zone of a player to 10 you need to add this under 3: myzone.zone.max-zone.1
# 10: myzone.zone.max-zone.2
# And when you add this permission 'myzone.zone.max-zone.2' the player will have a zone restriction of 10.
Restriction:
  BlockedFlags:
    - sleep
    - exit
    - game-mode
    - receive-chat
    - send-chat
  Size:
    (-1, -1, -1): myzone.zone.max-size.unlimited
    (50, 256, 50): myzone.zone.max-size.1
    (80, 256, 80): myzone.zone.max-size.2
    (100, 256, 100): myzone.zone.max-size.4
    (150, 256, 150): myzone.zone.max-size.3
  Zone:
    -1: myzone.zone.max-zone.unlimited
    3: myzone.zone.max-zone.1
    15: myzone.zone.max-zone.15
    7: myzone.zone.max-zone.7
    10: myzone.zone.max-zone.10
    4: myzone.zone.max-zone.4
    5: myzone.zone.max-zone.5
    10: myzone.zone.max-zone.10
    25: myzone.zone.max-zone.25
    100: myzone.zone.max-zone.100
```
