### ISSUE TITLE
Nem működik a bossbar és actionbar kiírás tiltása.

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#21]
```
Messages:
  Title:
    Enabled: true
    Permission: false
  ActionBar:
    Enabled: false
    Permission: false
  BossBar:
    Enabled: false
    Permission: false
```
